build(oci): fix `options.nimi` location
9e634742 introduced `options.nimi`
to use `options ? nimi` instead of `!(options ? systemd)`
in `recipes/packages/mox/service.nix`
however that requires `options.nimi` to be defined
in the modules of the modular service (now),
not the modules of `nimi.passthru.evalNimiModule` (before).

Without this fix, this was broken:
```console
$ nix -L build -f . apps.mox-app.oci.mox
error: The option `services.mox.configData."config/mox.conf".path' was accessed but has no value defined. Try setting the option.
```
because the `options ? nimi` case was always `false`,
never defining the aformentioned `path`.

This in turn was also broken:
```
nix -L build .#_forge-config
```

A secondary fix is to use `imports` instead of `lib.recursiveUpdate`.